class junit.framework.JUnit4TestAdapterCache$1 extends org.junit.runner.notification.RunListener
{
    final junit.framework.JUnit4TestAdapterCache this$0;
    final junit.framework.TestResult val$result;

    void <init>(junit.framework.JUnit4TestAdapterCache, junit.framework.TestResult)
    {
        junit.framework.JUnit4TestAdapterCache$1 r0;
        junit.framework.JUnit4TestAdapterCache r1;
        junit.framework.TestResult r2;

        r0 := @this: junit.framework.JUnit4TestAdapterCache$1;

        r1 := @parameter0: junit.framework.JUnit4TestAdapterCache;

        r2 := @parameter1: junit.framework.TestResult;

        r0.<junit.framework.JUnit4TestAdapterCache$1: junit.framework.JUnit4TestAdapterCache this$0> = r1;

        r0.<junit.framework.JUnit4TestAdapterCache$1: junit.framework.TestResult val$result> = r2;

        specialinvoke r0.<org.junit.runner.notification.RunListener: void <init>()>();

        return;
    }

    public void testFailure(org.junit.runner.notification.Failure) throws java.lang.Exception
    {
        junit.framework.JUnit4TestAdapterCache$1 r0;
        org.junit.runner.notification.Failure r1;
        junit.framework.TestResult $r2;
        junit.framework.JUnit4TestAdapterCache $r3;
        org.junit.runner.Description $r4;
        junit.framework.Test $r5;
        java.lang.Throwable $r6;

        r0 := @this: junit.framework.JUnit4TestAdapterCache$1;

        r1 := @parameter0: org.junit.runner.notification.Failure;

        $r2 = r0.<junit.framework.JUnit4TestAdapterCache$1: junit.framework.TestResult val$result>;

        $r3 = r0.<junit.framework.JUnit4TestAdapterCache$1: junit.framework.JUnit4TestAdapterCache this$0>;

        $r4 = virtualinvoke r1.<org.junit.runner.notification.Failure: org.junit.runner.Description getDescription()>();

        $r5 = virtualinvoke $r3.<junit.framework.JUnit4TestAdapterCache: junit.framework.Test asTest(org.junit.runner.Description)>($r4);

        $r6 = virtualinvoke r1.<org.junit.runner.notification.Failure: java.lang.Throwable getException()>();

        virtualinvoke $r2.<junit.framework.TestResult: void addError(junit.framework.Test,java.lang.Throwable)>($r5, $r6);

        return;
    }

    public void testFinished(org.junit.runner.Description) throws java.lang.Exception
    {
        junit.framework.JUnit4TestAdapterCache$1 r0;
        org.junit.runner.Description r1;
        junit.framework.JUnit4TestAdapterCache $r2;
        junit.framework.TestResult $r3;
        junit.framework.Test $r4;

        r0 := @this: junit.framework.JUnit4TestAdapterCache$1;

        r1 := @parameter0: org.junit.runner.Description;

        $r3 = r0.<junit.framework.JUnit4TestAdapterCache$1: junit.framework.TestResult val$result>;

        $r2 = r0.<junit.framework.JUnit4TestAdapterCache$1: junit.framework.JUnit4TestAdapterCache this$0>;

        $r4 = virtualinvoke $r2.<junit.framework.JUnit4TestAdapterCache: junit.framework.Test asTest(org.junit.runner.Description)>(r1);

        virtualinvoke $r3.<junit.framework.TestResult: void endTest(junit.framework.Test)>($r4);

        return;
    }

    public void testStarted(org.junit.runner.Description) throws java.lang.Exception
    {
        junit.framework.JUnit4TestAdapterCache$1 r0;
        org.junit.runner.Description r1;
        junit.framework.JUnit4TestAdapterCache $r2;
        junit.framework.TestResult $r3;
        junit.framework.Test $r4;

        r0 := @this: junit.framework.JUnit4TestAdapterCache$1;

        r1 := @parameter0: org.junit.runner.Description;

        $r3 = r0.<junit.framework.JUnit4TestAdapterCache$1: junit.framework.TestResult val$result>;

        $r2 = r0.<junit.framework.JUnit4TestAdapterCache$1: junit.framework.JUnit4TestAdapterCache this$0>;

        $r4 = virtualinvoke $r2.<junit.framework.JUnit4TestAdapterCache: junit.framework.Test asTest(org.junit.runner.Description)>(r1);

        virtualinvoke $r3.<junit.framework.TestResult: void startTest(junit.framework.Test)>($r4);

        return;
    }
}
