class org.junit.runner.notification.RunNotifier$5 extends org.junit.runner.notification.RunNotifier$SafeNotifier
{
    final org.junit.runner.notification.RunNotifier this$0;
    final org.junit.runner.notification.Failure val$failure;

    void <init>(org.junit.runner.notification.RunNotifier, org.junit.runner.notification.Failure)
    {
        org.junit.runner.notification.RunNotifier$5 r0;
        org.junit.runner.notification.RunNotifier r1;
        org.junit.runner.notification.Failure r2;

        r0 := @this: org.junit.runner.notification.RunNotifier$5;

        r1 := @parameter0: org.junit.runner.notification.RunNotifier;

        r2 := @parameter1: org.junit.runner.notification.Failure;

        r0.<org.junit.runner.notification.RunNotifier$5: org.junit.runner.notification.RunNotifier this$0> = r1;

        r0.<org.junit.runner.notification.RunNotifier$5: org.junit.runner.notification.Failure val$failure> = r2;

        specialinvoke r0.<org.junit.runner.notification.RunNotifier$SafeNotifier: void <init>(org.junit.runner.notification.RunNotifier)>(r1);

        return;
    }

    protected void notifyListener(org.junit.runner.notification.RunListener) throws java.lang.Exception
    {
        org.junit.runner.notification.RunNotifier$5 r0;
        org.junit.runner.notification.RunListener r1;
        org.junit.runner.notification.Failure $r2;

        r0 := @this: org.junit.runner.notification.RunNotifier$5;

        r1 := @parameter0: org.junit.runner.notification.RunListener;

        $r2 = r0.<org.junit.runner.notification.RunNotifier$5: org.junit.runner.notification.Failure val$failure>;

        virtualinvoke r1.<org.junit.runner.notification.RunListener: void testAssumptionFailure(org.junit.runner.notification.Failure)>($r2);

        return;
    }
}
