public class org.junit.internal.runners.MethodRoadie extends java.lang.Object
{
    private final org.junit.runner.Description description;
    private final org.junit.runner.notification.RunNotifier notifier;
    private final java.lang.Object test;
    private org.junit.internal.runners.TestMethod testMethod;

    public void <init>(java.lang.Object, org.junit.internal.runners.TestMethod, org.junit.runner.notification.RunNotifier, org.junit.runner.Description)
    {
        org.junit.internal.runners.MethodRoadie r0;
        java.lang.Object r1;
        org.junit.internal.runners.TestMethod r2;
        org.junit.runner.notification.RunNotifier r3;
        org.junit.runner.Description r4;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

        r1 := @parameter0: java.lang.Object;

        r2 := @parameter1: org.junit.internal.runners.TestMethod;

        r3 := @parameter2: org.junit.runner.notification.RunNotifier;

        r4 := @parameter3: org.junit.runner.Description;

        specialinvoke r0.<java.lang.Object: void <init>()>();

        r0.<org.junit.internal.runners.MethodRoadie: java.lang.Object test> = r1;

        r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.notification.RunNotifier notifier> = r3;

        r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.Description description> = r4;

        r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod> = r2;

        return;
    }

    private void runAfters()
    {
        org.junit.internal.runners.MethodRoadie r0;
        java.util.Iterator r1;
        org.junit.internal.runners.TestMethod $r2;
        java.util.List $r3;
        boolean $z0;
        java.lang.Object $r4, $r6;
        java.lang.Object[] $r5;
        java.lang.Throwable $r8, $r9, $r10;
        java.lang.reflect.Method r11;
        java.lang.reflect.InvocationTargetException r14;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

        $r2 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $r3 = virtualinvoke $r2.<org.junit.internal.runners.TestMethod: java.util.List getAfters()>();

        r1 = interfaceinvoke $r3.<java.util.List: java.util.Iterator iterator()>();

     label1:
        $z0 = interfaceinvoke r1.<java.util.Iterator: boolean hasNext()>();

        if $z0 == 0 goto label7;

        $r4 = interfaceinvoke r1.<java.util.Iterator: java.lang.Object next()>();

        r11 = (java.lang.reflect.Method) $r4;

     label2:
        $r6 = r0.<org.junit.internal.runners.MethodRoadie: java.lang.Object test>;

        $r5 = newarray (java.lang.Object)[0];

        virtualinvoke r11.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>($r6, $r5);

     label3:
        goto label6;

     label4:
        $r10 := @caughtexception;

        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void addFailure(java.lang.Throwable)>($r10);

        goto label6;

     label5:
        $r8 := @caughtexception;

        r14 = (java.lang.reflect.InvocationTargetException) $r8;

        $r9 = virtualinvoke r14.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();

        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void addFailure(java.lang.Throwable)>($r9);

     label6:
        goto label1;

     label7:
        return;

        catch java.lang.reflect.InvocationTargetException from label2 to label3 with label5;
        catch java.lang.Throwable from label2 to label3 with label4;
    }

    private void runBefores() throws org.junit.internal.runners.FailedBefore
    {
        org.junit.internal.runners.MethodRoadie r0;
        org.junit.internal.runners.TestMethod $r1;
        java.util.List $r2;
        boolean $z0;
        java.lang.Object $r3, $r5;
        java.lang.Object[] $r4;
        java.lang.reflect.Method $r6;
        org.junit.internal.AssumptionViolatedException $r8;
        java.lang.Throwable $r10, $r11, $r12;
        java.util.Iterator r14;
        org.junit.internal.runners.FailedBefore r18, r19;
        java.lang.reflect.InvocationTargetException r20;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

     label01:
        $r1 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $r2 = virtualinvoke $r1.<org.junit.internal.runners.TestMethod: java.util.List getBefores()>();

        r14 = interfaceinvoke $r2.<java.util.List: java.util.Iterator iterator()>();

     label02:
        $z0 = interfaceinvoke r14.<java.util.Iterator: boolean hasNext()>();

        if $z0 == 0 goto label04;

        $r3 = interfaceinvoke r14.<java.util.Iterator: java.lang.Object next()>();

        $r6 = (java.lang.reflect.Method) $r3;

        $r5 = r0.<org.junit.internal.runners.MethodRoadie: java.lang.Object test>;

        $r4 = newarray (java.lang.Object)[0];

        virtualinvoke $r6.<java.lang.reflect.Method: java.lang.Object invoke(java.lang.Object,java.lang.Object[])>($r5, $r4);

     label03:
        goto label02;

     label04:
        return;

     label05:
        $r12 := @caughtexception;

        goto label09;

     label06:
        $r8 := @caughtexception;

        goto label10;

     label07:
        $r10 := @caughtexception;

     label08:
        r20 = (java.lang.reflect.InvocationTargetException) $r10;

        $r11 = virtualinvoke r20.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();

        throw $r11;

     label09:
        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void addFailure(java.lang.Throwable)>($r12);

        r18 = new org.junit.internal.runners.FailedBefore;

        specialinvoke r18.<org.junit.internal.runners.FailedBefore: void <init>()>();

        throw r18;

     label10:
        r19 = new org.junit.internal.runners.FailedBefore;

        specialinvoke r19.<org.junit.internal.runners.FailedBefore: void <init>()>();

        throw r19;

        catch java.lang.reflect.InvocationTargetException from label01 to label02 with label07;
        catch org.junit.internal.AssumptionViolatedException from label01 to label02 with label06;
        catch java.lang.Throwable from label01 to label02 with label05;
        catch java.lang.reflect.InvocationTargetException from label02 to label03 with label07;
        catch org.junit.internal.AssumptionViolatedException from label02 to label03 with label06;
        catch java.lang.Throwable from label02 to label03 with label05;
        catch org.junit.internal.AssumptionViolatedException from label08 to label09 with label06;
        catch java.lang.Throwable from label08 to label09 with label05;
    }

    private void runWithTimeout(long)
    {
        org.junit.internal.runners.MethodRoadie r0;
        long l0;
        org.junit.internal.runners.MethodRoadie$1 $r1;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

        l0 := @parameter0: long;

        $r1 = new org.junit.internal.runners.MethodRoadie$1;

        specialinvoke $r1.<org.junit.internal.runners.MethodRoadie$1: void <init>(org.junit.internal.runners.MethodRoadie,long)>(r0, l0);

        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void runBeforesThenTestThenAfters(java.lang.Runnable)>($r1);

        return;
    }

    protected void addFailure(java.lang.Throwable)
    {
        org.junit.internal.runners.MethodRoadie r0;
        java.lang.Throwable r1;
        org.junit.runner.notification.Failure $r2;
        org.junit.runner.Description $r3;
        org.junit.runner.notification.RunNotifier $r4;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

        r1 := @parameter0: java.lang.Throwable;

        $r4 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.notification.RunNotifier notifier>;

        $r2 = new org.junit.runner.notification.Failure;

        $r3 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.Description description>;

        specialinvoke $r2.<org.junit.runner.notification.Failure: void <init>(org.junit.runner.Description,java.lang.Throwable)>($r3, r1);

        virtualinvoke $r4.<org.junit.runner.notification.RunNotifier: void fireTestFailure(org.junit.runner.notification.Failure)>($r2);

        return;
    }

    public void run()
    {
        org.junit.internal.runners.MethodRoadie r0;
        long l0;
        org.junit.internal.runners.TestMethod $r2, $r5;
        boolean $z0;
        org.junit.runner.Description $r3, $r6, $r8, $r11;
        org.junit.runner.notification.RunNotifier $r4, $r7, $r9, $r12;
        byte $b1;
        java.lang.Throwable $r10;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

        $r2 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $z0 = virtualinvoke $r2.<org.junit.internal.runners.TestMethod: boolean isIgnored()>();

        if $z0 == 0 goto label1;

        $r9 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.notification.RunNotifier notifier>;

        $r8 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.Description description>;

        virtualinvoke $r9.<org.junit.runner.notification.RunNotifier: void fireTestIgnored(org.junit.runner.Description)>($r8);

        return;

     label1:
        $r4 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.notification.RunNotifier notifier>;

        $r3 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.Description description>;

        virtualinvoke $r4.<org.junit.runner.notification.RunNotifier: void fireTestStarted(org.junit.runner.Description)>($r3);

     label2:
        $r5 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        l0 = virtualinvoke $r5.<org.junit.internal.runners.TestMethod: long getTimeout()>();

     label3:
        $b1 = l0 cmp 0L;

        if $b1 <= 0 goto label6;

     label4:
        specialinvoke r0.<org.junit.internal.runners.MethodRoadie: void runWithTimeout(long)>(l0);

     label5:
        goto label7;

     label6:
        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void runTest()>();

     label7:
        $r7 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.notification.RunNotifier notifier>;

        $r6 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.Description description>;

        virtualinvoke $r7.<org.junit.runner.notification.RunNotifier: void fireTestFinished(org.junit.runner.Description)>($r6);

        return;

     label8:
        $r10 := @caughtexception;

        $r12 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.notification.RunNotifier notifier>;

        $r11 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.runner.Description description>;

        virtualinvoke $r12.<org.junit.runner.notification.RunNotifier: void fireTestFinished(org.junit.runner.Description)>($r11);

        throw $r10;

        catch java.lang.Throwable from label2 to label3 with label8;
        catch java.lang.Throwable from label4 to label5 with label8;
        catch java.lang.Throwable from label6 to label7 with label8;
    }

    public void runBeforesThenTestThenAfters(java.lang.Runnable)
    {
        org.junit.internal.runners.MethodRoadie r0;
        java.lang.Exception $r1;
        java.lang.Throwable $r2;
        org.junit.internal.runners.FailedBefore $r3;
        java.lang.Runnable r4;
        java.lang.RuntimeException r7;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

        r4 := @parameter0: java.lang.Runnable;

     label1:
        specialinvoke r0.<org.junit.internal.runners.MethodRoadie: void runBefores()>();

        interfaceinvoke r4.<java.lang.Runnable: void run()>();

     label2:
        goto label8;

     label3:
        $r2 := @caughtexception;

        goto label6;

     label4:
        $r1 := @caughtexception;

     label5:
        r7 = new java.lang.RuntimeException;

        specialinvoke r7.<java.lang.RuntimeException: void <init>(java.lang.String)>("test should never throw an exception to this level");

        throw r7;

     label6:
        specialinvoke r0.<org.junit.internal.runners.MethodRoadie: void runAfters()>();

        throw $r2;

     label7:
        $r3 := @caughtexception;

     label8:
        specialinvoke r0.<org.junit.internal.runners.MethodRoadie: void runAfters()>();

        return;

        catch org.junit.internal.runners.FailedBefore from label1 to label2 with label7;
        catch java.lang.Exception from label1 to label2 with label4;
        catch java.lang.Throwable from label1 to label2 with label3;
        catch java.lang.Throwable from label5 to label6 with label3;
    }

    public void runTest()
    {
        org.junit.internal.runners.MethodRoadie r0;
        org.junit.internal.runners.MethodRoadie$2 $r1;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

        $r1 = new org.junit.internal.runners.MethodRoadie$2;

        specialinvoke $r1.<org.junit.internal.runners.MethodRoadie$2: void <init>(org.junit.internal.runners.MethodRoadie)>(r0);

        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void runBeforesThenTestThenAfters(java.lang.Runnable)>($r1);

        return;
    }

    protected void runTestMethod()
    {
        org.junit.internal.runners.MethodRoadie r0;
        java.lang.Object $r1;
        org.junit.internal.runners.TestMethod $r2, $r3, $r5, $r12, $r13, $r16;
        boolean $z0, $z1, $z2, $z3;
        java.lang.Class $r6, $r17, $r21;
        java.lang.String $r7, $r9, $r18, $r22, $r26;
        java.lang.Throwable $r10, $r11, r31;
        java.lang.StringBuilder r33, r35;
        java.lang.AssertionError r34;
        java.lang.Exception r36;
        java.lang.reflect.InvocationTargetException r37;

        r0 := @this: org.junit.internal.runners.MethodRoadie;

     label1:
        $r2 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $r1 = r0.<org.junit.internal.runners.MethodRoadie: java.lang.Object test>;

        virtualinvoke $r2.<org.junit.internal.runners.TestMethod: void invoke(java.lang.Object)>($r1);

        $r3 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $z0 = virtualinvoke $r3.<org.junit.internal.runners.TestMethod: boolean expectsException()>();

        if $z0 == 0 goto label7;

        r34 = new java.lang.AssertionError;

        r33 = new java.lang.StringBuilder;

        specialinvoke r33.<java.lang.StringBuilder: void <init>()>();

        virtualinvoke r33.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Expected exception: ");

        $r5 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $r6 = virtualinvoke $r5.<org.junit.internal.runners.TestMethod: java.lang.Class getExpectedException()>();

        $r7 = virtualinvoke $r6.<java.lang.Class: java.lang.String getName()>();

        virtualinvoke r33.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r7);

        $r9 = virtualinvoke r33.<java.lang.StringBuilder: java.lang.String toString()>();

        specialinvoke r34.<java.lang.AssertionError: void <init>(java.lang.Object)>($r9);

        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void addFailure(java.lang.Throwable)>(r34);

     label2:
        goto label7;

     label3:
        $r10 := @caughtexception;

        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void addFailure(java.lang.Throwable)>($r10);

        goto label7;

     label4:
        $r11 := @caughtexception;

        r37 = (java.lang.reflect.InvocationTargetException) $r11;

        r31 = virtualinvoke r37.<java.lang.reflect.InvocationTargetException: java.lang.Throwable getTargetException()>();

        $z1 = r31 instanceof org.junit.internal.AssumptionViolatedException;

        if $z1 == 0 goto label5;

        return;

     label5:
        $r12 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $z2 = virtualinvoke $r12.<org.junit.internal.runners.TestMethod: boolean expectsException()>();

        if $z2 != 0 goto label6;

        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void addFailure(java.lang.Throwable)>(r31);

        goto label7;

     label6:
        $r13 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $z3 = virtualinvoke $r13.<org.junit.internal.runners.TestMethod: boolean isUnexpected(java.lang.Throwable)>(r31);

        if $z3 == 0 goto label7;

        r35 = new java.lang.StringBuilder;

        specialinvoke r35.<java.lang.StringBuilder: void <init>()>();

        virtualinvoke r35.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("Unexpected exception, expected<");

        $r16 = r0.<org.junit.internal.runners.MethodRoadie: org.junit.internal.runners.TestMethod testMethod>;

        $r17 = virtualinvoke $r16.<org.junit.internal.runners.TestMethod: java.lang.Class getExpectedException()>();

        $r18 = virtualinvoke $r17.<java.lang.Class: java.lang.String getName()>();

        virtualinvoke r35.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r18);

        virtualinvoke r35.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>("> but was<");

        $r21 = virtualinvoke r31.<java.lang.Object: java.lang.Class getClass()>();

        $r22 = virtualinvoke $r21.<java.lang.Class: java.lang.String getName()>();

        virtualinvoke r35.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>($r22);

        virtualinvoke r35.<java.lang.StringBuilder: java.lang.StringBuilder append(java.lang.String)>(">");

        r36 = new java.lang.Exception;

        $r26 = virtualinvoke r35.<java.lang.StringBuilder: java.lang.String toString()>();

        specialinvoke r36.<java.lang.Exception: void <init>(java.lang.String,java.lang.Throwable)>($r26, r31);

        virtualinvoke r0.<org.junit.internal.runners.MethodRoadie: void addFailure(java.lang.Throwable)>(r36);

     label7:
        return;

        catch java.lang.reflect.InvocationTargetException from label1 to label2 with label4;
        catch java.lang.Throwable from label1 to label2 with label3;
    }
}
